// Computes the fastest racing line for every Ghost Lap circuit and writes games/ghost-lap/lines.js.
//
//   node scripts/optimize-lines.mjs [circuit ...]
//
// For each circuit: start from the elastic-band (least-curvature) line, optimise it for minimum lap
// time with the car model (race.js optimizeRacingLine), then prove it on the real physics: AI drivers
// at Impossible and Medium drive a flying lap on the old line and on the new one. The new line is kept
// only if it is quicker for both, with no track-limit strikes, corner cuts or wall hits, and if 20-car
// Grands Prix at Impossible on it finish without a single penalty; otherwise the
// circuit keeps the elastic-band line. Re-run it whenever the track geometry changes (a test checks
// that every stored line still matches its track).
import fs from "node:fs";
import { CIRCUITS } from "../games/ghost-lap/circuits.js";
import { buildTrack, optimizeRacingLine, trackShapeKey, createRace, stepRace, aiInput, DIFFICULTY } from "../games/ghost-lap/race.js";
import { RACING_LINES } from "../games/ghost-lap/lines.js";

const OUT = new URL("../games/ghost-lap/lines.js", import.meta.url);
const STEP = 2; // store every 2nd point (the line is smooth; it is interpolated back)
const only = process.argv.slice(2);
const CANDIDATES = [
  { margin: 24, passes: [[24, 12, 4, 3], [16, 6, 3, 3]] },
  { margin: 32, passes: [[24, 12, 4, 3], [16, 6, 3, 2]] },
  { margin: 32, passes: [[32, 10, 4, 3]] },
  { margin: 40, passes: [[24, 8, 4, 3]] }
];

function lap(key, lineEntry, level) {
  if (lineEntry) RACING_LINES[key] = lineEntry;
  else delete RACING_LINES[key];
  const track = buildTrack({ key, ...CIRCUITS[key] });
  const race = createRace({ track, mode: "trial", seed: 1 });
  const car = race.cars[0];
  car.isPlayer = false;
  race.player = null;
  car.skill = DIFFICULTY[level];
  let walls = 0;
  let cuts = 0;
  for (let k = 0; k < 120 * 240 && car.lapTimes.length < 2; k++) {
    stepRace(race, null, 1 / 120);
    if (car.wallHit === 0.3) walls++;
    for (const e of race.events) if (e.type === "cut") cuts++;
  }
  const l = car.lapTimes[1];
  const clean = !!l && l.valid && !car.strikes && !walls && !cuts;
  return { time: l ? l.time : Infinity, clean };
}

// A line must also survive racing: 20-car Grands Prix at Impossible with no penalties at all
function raceClean(key, lineEntry) {
  if (lineEntry) RACING_LINES[key] = lineEntry;
  else delete RACING_LINES[key];
  const track = buildTrack({ key, ...CIRCUITS[key] });
  for (const seed of [5, 6]) {
    const race = createRace({ track, mode: "gp", laps: 2, difficulty: "impossible", seed, brakes: true });
    for (let k = 0; k < 120 * 400 && !race.cars.every((c) => c.finished); k++) stepRace(race, aiInput(race.player, race, 1 / 120), 1 / 120);
    if (race.cars.some((c) => c.penalty || c.strikes || !c.finished)) return false;
  }
  return true;
}

const previous = { ...RACING_LINES };
const result = {};
let kept = 0;
for (const key of Object.keys(CIRCUITS)) {
  if (only.length && !only.includes(key)) {
    if (previous[key]) result[key] = previous[key];
    continue;
  }
  const base = buildTrack({ key, ...CIRCUITS[key], elasticLine: true });
  const t0 = Date.now();
  const levels = ["impossible", "medium"];
  const oldLaps = levels.map((lv) => lap(key, null, lv));
  const fmt = (ls) => ls.map((x) => `${x.time.toFixed(2)}${x.clean ? "" : "!"}`).join("/");
  // Candidate optimisations, boldest first; the quickest one that proves itself on the real physics wins
  let best = null;
  for (const opts of CANDIDATES) {
    const opt = optimizeRacingLine(base, null, opts);
    const offs = [];
    for (let i = 0; i < base.n; i += STEP) offs.push(Math.round(opt.line[i] * 10) / 10);
    const entry = { shape: trackShapeKey(base.path), step: STEP, offs };
    const newLaps = levels.map((lv) => lap(key, entry, lv));
    const ok = newLaps.every((nl, k) => nl.clean && nl.time < oldLaps[k].time - 0.02) && raceClean(key, entry);
    const total = newLaps.reduce((a, x) => a + x.time, 0);
    console.log(`${key.padEnd(12)} margin ${opts.margin} bumps ${opts.passes.map((p) => p[0]).join("/")}: model ${opt.start.toFixed(2)} -> ${opt.time.toFixed(2)} | AI old ${fmt(oldLaps)} new ${fmt(newLaps)}${ok ? "  ✓" : ""}`);
    if (ok && (!best || total < best.total)) best = { entry, total };
    if (ok && opts === CANDIDATES[0]) break;
  }
  console.log(`${key.padEnd(12)} => ${best ? "NEW LINE" : "kept old"} (${((Date.now() - t0) / 1000).toFixed(1)}s)`);
  if (best) {
    result[key] = best.entry;
    kept++;
  }
  delete RACING_LINES[key];
}

let src = "// Fastest racing lines, generated by scripts/optimize-lines.mjs (do not edit by hand).\n";
src += "// Per circuit: the track-shape fingerprint it was made for, and the line's offset from the\n";
src += `// centreline (px) at every ${STEP}nd point.\nexport const RACING_LINES = {\n`;
for (const [key, v] of Object.entries(result)) src += `  ${key}: { shape: "${v.shape}", step: ${v.step}, offs: [${v.offs.join(",")}] },\n`;
src += "};\n";
fs.writeFileSync(OUT, src);
console.log(`\n${kept} circuits got a faster line; lines.js written (${(src.length / 1024).toFixed(0)} KB)`);
